name: ByLine

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: ".byline"
        FILE_DATA: "user: {{ GITHUB_ACTOR}}\nrepo: $GITHUB_REPOSITORY$"
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .byline
        git commit -m "User Byline Generated"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
